### ISSUE TITLE
Python version compatibility

### ISSUE THREAD

**Issue by zhexingli** [chenjj2/forecaster#7]
Hello,
I don't think this code is compatibile with the new python versions, most obviously the print statements... no big changes needed tho.

**Comment by zhexingli** [comment]
Error came up when running the code to get radius from mass values, everything was fine when running code to get mass from radius:

Traceback (most recent call last):
  File "/Users/ZhexingLi/anaconda/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ZhexingLi/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "/Users/ZhexingLi/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/Users/ZhexingLi/Desktop/untitled0.py", line 15, in <module>
    Mmedian, Mplus, Mminus = mr.Rstat2M(mean=1.0, std=0.01, unit='Jupiter', sample_size=100, grid_size=1e3, classify='Yes')
  File "/Users/ZhexingLi/anaconda/lib/python3.6/site-packages/forecast/mr_forecast.py", line 260, in Rstat2M
    else:
  File "/Users/ZhexingLi/anaconda/lib/python3.6/site-packages/forecast/mr_forecast.py", line 203, in Rpost2M
    
  File "<__array_function__ internals>", line 6, in linspace
  File "/Users/ZhexingLi/anaconda/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

**Comment by zhexingli** [comment]
nvm, looks like python is having issue with scientific notation, not sure why...
